# compose.prod.yaml - Production deployment på cloud VM
# Krav 5: Bruger 'image:' i stedet for 'build:'

version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: todo-mysql-prod
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tododb}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data-prod:/var/lib/mysql
    # Ingen port mapping - kun tilgængelig internt (sikkerhed)
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s

  # Spring Boot Backend - Henter fra GHCR (krav: image: ghcr.io/...)
  backend:
    image: ghcr.io/huw02/team-48-todo-deployment-backend:latest
    container_name: todo-backend-prod
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-tododb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:8080:8080"  # Kun tilgængelig via localhost (nginx proxy)
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/status/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - Henter fra GHCR
  frontend:
    image: ghcr.io/huw02/team-48-todo-deployment-frontend:latest
    container_name: todo-frontend-prod
    restart: always
    ports:
      - "127.0.0.1:3000:80"  # Kun tilgængelig via localhost (nginx proxy)
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql-data-prod:
    driver: local

networks:
  app-network:
    driver: bridge